type User {
  email: String!
  files: [File!]!
  playgrounds: [Playground!]!
  name: String!
  id: ID!
}

type UserResponse {
  user: User
  errors: [FieldError]
}

type FieldError {
  path: String!
  message: String!
}

type Query {
  me: User
}

type Mutation {
  register(email: String!, password: String!, name: String!): UserResponse!
  login(email: String!, password: String!): UserResponse!
  logout: Boolean!
}
