type Playground {
  name: String!
  files: [File!]
  id: ID!
  createdAt: Date!
  updatedAt: Date!
}

type Query {
  getPlayground(id: ID!): Playground
}

input UpdatePlaygroundInput {
  id: ID!
  name: String
}

type Mutation {
  createPlayground(name: String!): Playground!
  updatePlayground(data: UpdatePlaygroundInput!): Playground!
  deletePlayground(id: ID!): Playground!
}

type Subscription {
  playground(id: ID!): Int
}
